/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UniversityIndexRouteImport } from './routes/university.index'
import { Route as UniversityUniRouteImport } from './routes/university.$uni'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityIndexRoute = UniversityIndexRouteImport.update({
  id: '/university/',
  path: '/university/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityUniRoute = UniversityUniRouteImport.update({
  id: '/university/$uni',
  path: '/university/$uni',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/university/$uni': typeof UniversityUniRoute
  '/university': typeof UniversityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/university/$uni': typeof UniversityUniRoute
  '/university': typeof UniversityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/university/$uni': typeof UniversityUniRoute
  '/university/': typeof UniversityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/university/$uni' | '/university'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/university/$uni' | '/university'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/university/$uni'
    | '/university/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  UniversityUniRoute: typeof UniversityUniRoute
  UniversityIndexRoute: typeof UniversityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/': {
      id: '/university/'
      path: '/university'
      fullPath: '/university'
      preLoaderRoute: typeof UniversityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/$uni': {
      id: '/university/$uni'
      path: '/university/$uni'
      fullPath: '/university/$uni'
      preLoaderRoute: typeof UniversityUniRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  UniversityUniRoute: UniversityUniRoute,
  UniversityIndexRoute: UniversityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
